defaults:
  - solver: solver
  - data@data.train: purchases_train
  - data@data.val: purchases_val
  - training: purchases
  - logging: default_logging
  - model@model: ziln_mlp
  - metrics@metrics: default_metrics

data:
  train:
    mode: "train"
  val:
    mode: "val"
    dataloader:
      batch_size: 2