_target_: src.trainer.NeuralSolver
_recursive_: false
model: ${model}
loss: src.losses.ziln_loss
  #_target_: torch.nn.L1Loss
train_loader: ${data.train.dataloader}
val_loader: ${data.val.dataloader}
metric_fns: ${metrics.metric_fns}
n_epochs: ${..training.n_epochs}
optimizer: ${..training.optimizer}
early_stopping_rounds: ${..training.early_stopping_rounds}
logger: ${..logging}
save_dir: "models"
model_name: "ziln_mlp.pt"
device: ${training.device}